version: '3.2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jsteven
      POSTGRES_PASSWORD: jsteven
      POSTGRES_DB: platziverse
      
  app_mqtt:
    build: ./platziverse-mqtt
    ports: 
      - 1883:1883
    depends_on: 
      - redis
      - db
    links:
      - redis
      - db
    volumes:
      - type: volume
        source: .
        target: /usr/src/app

  redis:
    image: "redis"
  
  app_agent:
    build: ./platziverse-agent/
    depends_on: 
      - app_mqtt
    links:
      - app_mqtt
    volumes:
      - type: volume
        source: .
        target: /usr/src/app

  app_api:
      build: ./platziverse-api/
      ports:
        - 3000:3000
      volumes:
        - type: volume
          source: .
          target: /usr/src/app

